const CURRENT_HISTORY_WINDOW_SIZE = 2000
const PREVIOUS_HISTORY_WINDOW_START = 3000
const PREVIOUS_HISTORY_WINDOW_END =  1000
const HISTORY_LENGTH = 3
const MULTIPLIER = 0.925

export {
    CURRENT_HISTORY_WINDOW_SIZE,
    PREVIOUS_HISTORY_WINDOW_START,
    PREVIOUS_HISTORY_WINDOW_END,
    HISTORY_LENGTH,
    MULTIPLIER
}